### ISSUE TITLE
[patch] Wrong range start value in debug message

### ISSUE THREAD

**Issue by nms42** [lvs1974/RTCMemoryFixup#2]
After for(;;) soffset is beyond eoffset. )-;

[rtcfx.diff.txt](https://github.com/lvs1974/RTCMemoryFixup/files/2571784/rtcfx.diff.txt)

**Comment by nms42** [comment]
Oops! Forgot about the sample of wrong text

RTCMemoryFixup:   RTCFX @ (DBG) boot-arg rtcfx_exclude specified, value = 80-FF
RTCMemoryFixup:   RTCFX @ (DBG) rtc offset token = 80-FF
RTCMemoryFixup:   RTCFX @ (DBG) rtc range from offset 100 to offset FF is marked as emulated

**Comment by lvs1974** [comment]
Thank you for the notice and fixe!
